nginx:
    image: tutum/nginx
    container_name: nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        #- ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
phpfpm:
    image: bitnami/php-fpm:7.0
    container_name: php7
    ports:
        - "9000:9000"
    volumes:
        - ./www:/usr/share/nginx/html
mysql:
    image: mariadb
    container_name: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: admin
    ports:
        - "3306:3306" 
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyadmin
    restart: always
    links:
        - mysql
    ports:
        - 8183:80
    environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: admin
        PMA_ARBITRARY: 1    